### ISSUE TITLE
Client secret in public code.

### ISSUE THREAD

**Issue by dseomn** [whaliam/Bobrossbot#2]
I just noticed what looks like an [API secret in the code](https://github.com/whaliam/Bobrossbot/blob/2912d8e5720dc2f58323699ac8113c42368660b9/BobRossBotv0.4.py#L23). If that is what it is, you might want to read it from somewhere else instead of hardcoding, and then change the secret.

**Comment by whaliam** [comment]
It is an API key I'm not sure how to delete the commit however the bot's current API key has been changed. Thanks :)
